version: '3.1'

services:

   mysql:
     image: mysql:latest
     container_name: mysql_container
     ports:
       - "3307:3306"
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: transactions
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_USER: redolf
     volumes:
       - mysql_data:/var/lib/mysql

   rancard:
     image: rancard-assessment:latest
     container_name: rancard-assessment-container
     ports:
         - "9091:8080"
     environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/transactions?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Africa%2FNairobi&useSSL=false;
          SPRING_DATASOURCE_USERNAME: redolf
     links:
        - mysql
volumes:
   mysql_data:



