version: '3'

services:
    mysql:
        image: mysql:latest
        container_name: mysql_container
        ports:
          - "3307:3306"
          - "3308:3306"
          - "3309:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: transactions
           MYSQL_PASSWORD: user
           MYSQL_USER: user
        volumes:
          - mysql_data:/var/lib/mysql
        networks:
          - rancard-assessment

    rancard:
         image: rancard-assessment:latest
         container_name: rancard-assessment-container
         ports:
            - "9091:8080"
         environment:
            DB_DATABASE: transactions
            DB_USERNAME: user
            DB_USER_PASSWORD: user
         networks:
            - rancard-assessment
         links:
            - mysql
networks:
  rancard-assessment:
    driver: bridge

volumes:
  mysql_data:

