DB_USERNAME=root;DB_DATABASE=transactions;DB_USER_PASSWORD=0552588647

server:
    port: 8080
spring:
    application:
        name: ASSESSMENT
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3309/${DB_DATABASE}
        username: ${DB_USERNAME}
        password: ${DB_USER_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
    main:
        allow-circular-references: true
